# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
 name: k8skeda

jobs:
- job: A
  timeoutInMinutes: 240
  steps:

  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - task: PowerShell@2
    timeoutInMinutes: 240
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        
        Start-Sleep -Seconds 10800

  - script: echo Finish!
    displayName: 'Finish script'