apiVersion: v1  
kind: Namespace  
metadata:  
  name: azdo
---
apiVersion: v1
kind: Secret
metadata:
  name: azdevops
  namespace: azdo
stringData:
  AZP_TOKEN: '!AZDO_PAT_TOKEN!'
  AZP_URL: 'https://dev.azure.com/rmoreiraoms'
  AZP_POOL: 'k8skeda'