apiVersion: v1
kind: Namespace
metadata:
  name: workload
  labels:
    name: workload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp01-deployment
  namespace: workload
  labels:
    app: webapp01
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: webapp01
  template:
    metadata:
      labels:
        app: webapp01
    spec:
      containers:
      - name: webapp01
        image: acraksinaday.azurecr.io/webapp01:latest
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
          limits:
            cpu: 750m
            memory: 512Mi
        ports:
        - containerPort: 80
          protocol: TCP