apiVersion: v1
kind: Namespace
metadata:
  name: workload
  labels:
    name: workload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp01-deployment
  namespace: workload
  labels:
    app: webapp01
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: webapp01
  template:
    metadata:
      labels:
        app: webapp01
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: webapp01
        image: acraksinaday.azurecr.io/webapp01:latest
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
          limits:
            cpu: 750m
            memory: 512Mi
        ports:
        - containerPort: 80
          protocol: TCP
---
# service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp01
  name: webapp01-service
  namespace: workload
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: webapp01
  type: LoadBalancer