apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment-heavy
  namespace: azdo
  labels:
    app: azdevops-agent
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
        - name: azdo
          image: acraksinaday.azurecr.io/azdowin:latest
          resources:
            requests:
              cpu: 1000m
              memory: 1000Mi
            limits:
              cpu: 2000m
              memory: 2000Mi
          env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_TOKEN
          - name: AZP_POOL
            value: aks-heavy
          volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment-middle
  namespace: azdo
  labels:
    app: azdevops-agent
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
        - name: azdo
          image: acraksinaday.azurecr.io/azdowin:latest
          resources:
            requests:
              cpu: 1000m
              memory: 1000Mi
            limits:
              cpu: 2000m
              memory: 2000Mi
          env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_TOKEN
          - name: AZP_POOL
            value: aks-middle
          volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment-light
  namespace: azdo
  labels:
    app: azdevops-agent
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
        - name: azdo
          image: acraksinaday.azurecr.io/azdowin:latest
          resources:
            requests:
              cpu: 1000m
              memory: 1000Mi
            limits:
              cpu: 2000m
              memory: 2000Mi
          env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_TOKEN
          - name: AZP_POOL
            value: aks-light
          volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock