apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata: 
  name: pipeline-trigger-auth
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: azdevops
      key: AZP_TOKEN
    - parameter: organizationURL
      name: azdevops
      key: AZP_URL