kind: Pod
apiVersion: v1
metadata:
  name: busybox-secrets-store-inline
  namespace: azdo
spec:
  containers:
    - name: busybox
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      command:
        - "/bin/sleep"
        - "10000"
      volumeMounts:
      - name: secrets-store01-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
      env:
      - name: AZP_TOKEN
        valueFrom:
          secretKeyRef:
            name: azdevopsk8s
            key: K8S-AZP-TOKEN
  volumes:
    - name: secrets-store01-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kvname-user-msi"