# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: azdo
spec:
  provider: azure
  secretObjects:
  - data:
    - objectName: K8S-AZP-TOKEN
      key: K8S-AZP-TOKEN
    - objectName: K8S-AZP-URL
      key: K8S-AZP-URL
    - objectName: K8S-AZP-POOL
      key: K8S-AZP-POOL
    secretName: azdevopsk8s
    type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    # userAssignedIdentityID: "5b8727db-993b-49e6-ac03-f3495c0ca968"   # Set the clientID of the user-assigned managed identity to use
    userAssignedIdentityID: "a941d5da-f47e-43fc-8f3e-5b3919e8d069" # Set the clientID of the user-assigned managed identity to use
    keyvaultName: kv-aks-01     # Set to the name of your key vault
    tenantId: "16b3c013-d300-468d-ac64-7eda0820b6d3"                 # The tenant ID of the key vault
    objects:  |
      array:
        - |
          objectName: K8S-AZP-TOKEN
          objectType: secret
        - |
          objectName: K8S-AZP-URL
          objectType: secret
        - |
          objectName: K8S-AZP-POOL
          objectType: secret
  